{% set name = "lupa" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lupa-{{ version }}.tar.gz
  sha256: 5300d21f81aa1bd4d45f55e31dddba3b879895696068a3f84cfcb5fd9148aacd

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gcc  # [linux]
  host:
    - python
    - cython
    - pip
    - setuptools
    - lua
    - luajit
  run:
    - python

test:
  imports:
    - lupa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scoder/lupa
  summary: Python wrapper around Lua and LuaJIT
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lincrosenbach
    - mv-per
    - brnomendes
    - mediocretech
